---
title: "How to use R to hack the publicly available data about skills of 2M+ worldwide students?"
author:
 - name: "Przemyslaw Biecek"
   affiliation: [1]
   email: "przemyslaw.biecek@gmail.com"
   contact: yes
affiliation:
 - "University of Warsaw"
keywords: "visualisation; survey data; archivist; data mining"
packages: "ggplot2; shiny; intsvy; archivist; knitr; BetaBit; PISA2012lite"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

During the talk I will introduce The Programme for International Student
Assessment (PISA), an international survey that aims to evaluate
education systems worldwide. It’s a source of large data about
educational performance and various other characteristics of over 2 000
000 students from 62 countries. The data from the last PISA assessment
is available in the **R** package.

To play with it we will use packages and to explain the relation between
parental occupation and student’s performance. Then we will overview the
package -- the toolbox for statistical analyses of international surveys.
Finally we will discuss applications of packages and and the role of
reproducibility and traceability of results. At the end I will introduce the project that aims to boost data science
skills of students.

<!--  -->
<!-- **References** -->
<!-- @Manual{,
  title = {{intsvy}: International Assessment Data Manager},
  author = Daniel Caro and Przemys{\l}aw},
  year = {2015},
  url = {http://users.ox.ac.uk/~educ0279/}
  }
 
  @article{,
  title = {Do parents' occupations have an impact on student performance?},
  author = {Przemyslaw Biecek and Francesca Borgonovi},
  year = {2012},
  url = {PISA in Focus n. 36, 2012}
  }
 
  @Manual{,
  title = {{archivist}: An {R} Package for Managing, Recording and
  Restoring Data Analysis Results},
  author = {Przemyslaw Biecek and Marcin Kosinski},
  year = {2016},
  url = {https://github.com/pbiecek/archivist},
  } -->
