---
title: "Wrestling with big data in forestry: use of R in Scots pine site index analysis."
author:
 - name: "Wojciech Kędziora"
   affiliation: [1]
   email: "wojciech.kedziora@wl.sggw.pl"
   contact: yes
 - name: "Robert Tomusiak"
   affiliation: [2]
affiliation:
 - "Department of Forest Management Planning, Geomatics and Forest Economics, Warsaw University of Life Sciences – SGGW"
 - "Laboratory of Dendrometry and Forest Productivity, Warsaw University of Life Sciences – SGGW"
keywords: "national forest inventory; permanent plots; site index"
packages: ""
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

National Forest Inventory (NFI) supplies high resolution data on forests
of all property forms located throughout the country. These data are
collected from the circular sample plots uniformly distributed in grid
of squares 4 by 4 km. In Poland, around ~27,900 sample plots were
established. Recently, the second measuring cycle NFI was completed,
which, in addition to a potentially wide range of spatial analysis,
creates a unique opportunity to analyze the change in the pattern of
tree growth through time, giving opportunity to describe the reaction of
species to changes of environmental conditions. NFI data give a great
opportunity to determine one of the most important forest habitat’s
productivity factors -- site index. It is often expressed as the average
height of the trees of the target species at a given age. Determination
of the site index for the dominant species in the stand allows one to
characterize its growth potential in examined habitat conditions. The
project envisages the use of empirical data collected in NFI to
determine the structure of pine stands site index in Poland. Relatively
high number of sample plots and complicated computations as well as
future need for geostatistical analyses were reasons to choose **R**
environment to work successfully with forestry big data.

<!--  -->
<!--  -->
<!--  -->
