---
title: "R as an Environment for the Reproducible Analysis of DNA Amplification Experiments"
author:
 - name: "Stefan Rödiger"
   affiliation: [1]
   email: "stefan.roediger@b-tu.de"
   contact: yes
 - name: "Michal Burdukiewic"
   affiliation: [2]
 - name: "Peter Schierac"
   affiliation: [1]
affiliation:
 - "Institute of Biotechnology, Brandenburg University of Technology Cottbus-Senftenberg"
 - "Department of Genomics, University of Wroclaw"
keywords: "bioinfrmatics; qPCR; digital PCR; reproducible research;non-linear regression; smoothing; pre-processingI;"
packages: "chipPCR; dpcR; MBmca; RDML; rkwarddev; qpcR"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Quantitative PCR (qPCR), digital PCR (dPCR), quantitative isothermal amplification (qIA) and melting curve analysis (MCA) are key technologies in molecular diagnostics, forensics and life sciences. However, software for the biostatistical data analysis of such technologies is either tied to a specific task or part of a monolithic closed source software. This limits the reproducibility of computations and gives no control over the analysis algorithms. 

We contributed bioinformatics software tools for reproducible and transparent data analysis. Analysis pipelines consisting of statistical procedures, raw data  preprocessing, analysis, charts and report generation are implemented for increasingly demanded reproducible research. This is achieved with our packages *MBmca*, *chipPCR*, *dpcR* and *RDML*. We implemented selected findings for the **R** GUI/IDE RKWard and as *shiny* web browser applications. For rapid prototyping of RKWard plugins we used the *rkwarddev* package.
 
In our exemplary workflows we show analyzers for qPCR, qIA, MCA and dPCR experiments, which can be build in short development cycles. Our software is targeted at users who develop novel devices or users who wish to analyze raw and unprocessed data.
<!--  -->
<!-- **References** -->
<!-- @Article{rodiger_surface_2013,
  Title = {Surface {Melting} {Curve} {Analysis} with {R}},
  Author = {R\"{o}diger, Stefan and B\"{o}hm, Alexander and Schimke, Ingolf},
  Journal = {The R Journal},
  Year = {2013},
  Number = {2},
  Pages = {37--53},
  Volume = {5},
 
  Url = {http://journal.r-project.org/archive/2013-2/RJournal_2013-2_roediger-bohm-schimke.pdf}
 }
 
 @Article{rodiger_r_2015,
  Title = {R as an {Environment} for the {Reproducible} {Analysis} of {DNA} {Amplification} {Experiments}},
  Author = {R\"{o}diger, Stefan and Burdukiewicz, Micha\l{} and Blagodatskikh, Konstantin A. and Schierack, Peter},
  Journal = {The R Journal},
  Year = {2015},
  Number = {2},
  Pages = {127--150},
  Volume = {7},
 
  Url = {http://journal.r-project.org/archive/2015-1/RJ-2015-1.pdf}
 }
 
 @Article{rodiger_chippcr:_2015,
  Title = {{chipPCR}: an {R} package to pre-process raw data of amplification curves},
  Author = {R\"{o}diger, Stefan and Burdukiewicz, Micha\l{} and Schierack, Peter},
  Journal = {Bioinformatics},
  Year = {2015},
 
  Month = sep,
  Number = {17},
  Pages = {2900--2902},
  Volume = {31},
 
  Abstract = {Motivation: Both the quantitative real-time polymerase chain reaction (qPCR) and quantitative isothermal amplification (qIA) are standard methods for nucleic acid quantification. Numerous real-time read-out technologies have been developed. Despite the continuous interest in amplification-based techniques, there are only few tools for pre-processing of amplification data. However, a transparent tool for precise control of raw data is indispensable in several scenarios, for example, during the development of new instruments.
 Results: chipPCR is an R package for the pre-processing and quality analysis of raw data of amplification curves. The package takes advantage of R’s S4 object model and offers an extensible environment. chipPCR contains tools for raw data exploration: normalization, baselining, imputation of missing values, a powerful wrapper for amplification curve smoothing and a function to detect the start and end of an amplification curve. The capabilities of the software are enhanced by the implementation of algorithms unavailable in R, such as a 5-point stencil for derivative interpolation. Simulation tools, statistical tests, plots for data quality management, amplification efficiency/quantification cycle calculation, and datasets from qPCR and qIA experiments are part of the package. Core functionalities are integrated in GUIs (web-based and standalone shiny applications), thus streamlining analysis and report generation.
 Availability and implementation: http://cran.r-project.org/web/packages/chipPCR. Source code: https://github.com/michbur/chipPCR.
 Contact: stefan.roediger@b-tu.de
 Supplementary information: Supplementary data are available at Bioinformatics online.},
  Doi = {10.1093/bioinformatics/btv205},
  ISSN = {1367-4803, 1460-2059},
  Language = {en},
  Pmid = {25913204},
  Shorttitle = {{chipPCR}},
  Url = {http://bioinformatics.oxfordjournals.org/content/31/17/2900},
  Urldate = {2015-09-08}
 }
 
 @Article{rodiger_rkward:_2012,
  Title = {{RKWard}: {A} {Comprehensive} {Graphical} {User} {Interface} and {Integrated} {Development} {Environment} for {Statistical} {Analysis} with {R}},
  Author = {R\"{o}diger, Stefan and Friedrichsmeier, Thomas and Kapat, Prasenjit and Michalke, Meik},
  Journal = {Journal of Statistical Software},
  Year = {2012},
  Number = {9},
  Pages = {1--34},
  Volume = {49},
 
  ISSN = {1548-7660},
  Url = {http://www.jstatsoft.org/v49/i09}
 }
 
 @Article{spiess_impact_2015,
  Title = {Impact of {Smoothing} on {Parameter} {Estimation} in {Quantitative} {DNA} {Amplification} {Experiments}},
  Author = {Spiess, Andrej-Nikolai and Deutschmann, Claudia and Burdukiewicz, Micha\l{} and Himmelreich, Ralf and Klat, Katharina and Schierack, Peter and R\"{o}diger, Stefan},
  Journal = {Clinical Chemistry},
  Year = {2015},
 
  Month = feb,
  Number = {2},
  Pages = {379--388},
  Volume = {61},
 
  Abstract = {BACKGROUND: Quantification cycle (Cq) and amplification efficiency (AE) are parameters mathematically extracted from raw data to characterize quantitative PCR (qPCR) reactions and quantify the copy number in a sample. Little attention has been paid to the effects of preprocessing and the use of smoothing or filtering approaches to compensate for noisy data. Existing algorithms largely are taken for granted, and it is unclear which of the various methods is most informative. We investigated the effect of smoothing and filtering algorithms on amplification curve data.
 METHODS: We obtained published high-replicate qPCR data sets from standard block thermocyclers and other cycler platforms and statistically evaluated the impact of smoothing on Cq and AE.
 RESULTS: Our results indicate that selected smoothing algorithms affect estimates of Cq and AE considerably. The commonly used moving average filter performed worst in all qPCR scenarios. The Savitzky–Golay smoother, cubic splines, and Whittaker smoother resulted overall in the least bias in our setting and exhibited low sensitivity to differences in qPCR AE, whereas other smoothers, such as running mean, introduced an AE-dependent bias.
 CONCLUSIONS: The selection of a smoothing algorithm is an important step in developing data analysis pipelines for real-time PCR experiments. We offer guidelines for selection of an appropriate smoothing algorithm in diagnostic qPCR applications. The findings of our study were implemented in the R packages chipPCR and qpcR as a basis for the implementation of an analytical strategy.},
  Doi = {10.1373/clinchem.2014.230656},
  ISSN = {0009-9147, 1530-8561},
  Language = {en},
  Pmid = {25477537},
  Url = {http://www.clinchem.org/content/61/2/379},
  Urldate = {2015-04-01}
 } -->
