---
title: "Aargh I have to teach R (Experiences in the teaching of R)"
author:
 - name: "Martin Schneider"
   affiliation: [1]
   email: "martin.schneider@eoda.de"
   contact: yes
affiliation:
 - "eoda GmbH"
keywords: "teaching; training"
packages: "shiny"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

As **R** is gaining popularity, so there is the interest in **R** courses. **R**,
generally considered as a programming language with a steep learning
curve, has surely its own typical pitfalls. The aim of this talk is to give an overview of the general do’s and
don’ts regarding the teaching of **R** and how a typical **R** course can be
designed. Design and execution of a course depend on a variety of
influences such as different types of course participants, content and
context. Course participants usually differ regarding prior knowledge,
interest in the material, ambitions as well as objectives to be reached. Generally, **R** courses focus either more on statistical or on
programming topics. Another crucial aspect is whether the participants
come from an academic or an industrial background, in other words, the
context in which the course takes place. The talk is based on the
experiences of an **R** trainer teaching **R** to academics, as well as in
companies, with a topic area ranging from teaching the fundamentals to
specialised workshops (e.g. performing a Network Analysis in a *shiny* app).

<!--  -->
<!--  -->
<!--  -->
