---
title: "Modelling the distrubution of the bryophytes in different spatial scales"
author:
 - name: "Sylwia Wierzcholska"
   affiliation: [1]
   email: "sylwia.wierzcholska@gmail.com"
   contact: yes
 - name: "Marcin K. Dyderski"
   affiliation: [2,3]
 - name: "Andrzej M. Jagodziński"
   affiliation: [2,3]   
affiliation:
 - "Białowieża Geobotanical Station, University of Warsaw"
 - "Institute of Dendrology, Polish Academy of Sciences"
 - "Department of Game Management and Forest Protection, Poznań University of Life Sciences"
keywords: "species distribution model, biodiversity, plant ecology, predictive modelling, mosses, forest"
packages: "dismo, rasterVis"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Species distribution models (SDM) are mathematical models describing distribution of species within environmental (ecological) and geographical space. These models are used for biodiversity conservation in two ways: to find out threatened species requirements and to predict spread of invasive species. We aimed to model distribution of model bryophyte species -- *Dicranum viride* -- in Poland and in Europe and compare its ecological niches obtained by these two models. We chose *D. viride*, as this easily-recognizable species is a subject of Natura 2000 protection and an ancient forest species. Thus, it may be an umbrella species for numerous bryophyte species occurring on decaying wood and in old woodlands. 
We used data from Global Biodiversity Information Facility (http://www.gbif.org), published papers and herbarium collections to find out complete information about *D. viride* localities. As most of data about species distribution for large areas is presence-only data, we used MaxEnt model from *dismo* package, which is developed to processing this type of input data. As the explanatory variables we used 19 bioclimatic statistics from WordlClim database, available in 2.5’ grid and, in case of model for Poland only, data about share of old (>100 years old) forests within grid square. We also analyzed data about phorophyte species and collection year.
Model developed by MaxEnt is a probalistic model, which due to Receiver-Operator Curve allow to manage the threshold of species occurence, and thus – its restrictiveness. Our model has shown importance of particular bioclimatic variables and potential distribution of species. Obtained results allow us to conclude about climatic requirements of species studied and its potential habitats, where species may be found or may be protected ex situ. SDMs are very usefull tool for plant geography, biodiversity conservation and ecology.

<!--  -->
<!--  -->
<!--  -->
