---
title: "Embedding R in business processes"
author:
 - name: "Andreas Wygrabek"
   affiliation: [1]
   email: "andreas.wygrabek@eoda.de"
   contact: yes
affiliation:
 - "eoda GmbH"
keywords: "business; process integration"
packages: ""
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

There is no doubt about it: a variety of implemented statistical methods
that are easy to access can make **R** a valuable tool for plenty
application scenarios in business e.g. planning sales campaigns,
monitoring machines, acceptance sampling on incoming goods or in-process
control. All these scenarios are ruled by standardized business
processes and tied with substantial financial risks. Beside the
analytical capabilities of **R**, there are two main requirements on **R** that
are important for companies: on the one hand **R** needs to be smoothly
integrated into existing business processes. On the other hand, **R** needs
to be a reliable part of the process chain: secure, easy to maintain,
automatable and integrable into a right management system. Even though **R**
reaches an incredible popularity many companies struggle to make **R** more
than a proof of concept tool. The maturity level of **R** is reached when it
has become crutial a part of business process chains. The talk will
delight the main questions and critical issues of making **R** an essential
link in a business process chain. Furthermore the talk will present some
state of the art strategies to face the depicted issues regarding
security, reliability and automatization in operating systems.

<!--  -->
<!--  -->
<!--  -->
