---
title: "Dynamic Inflation Rate Calculation of Fast-Moving Consumer Goods: Shiny-SparkR App"
author:
 - name: "Olgun Aydin"
   affiliation: [1]
   email: "olgunaydinn@gmail.com"
   contact: yes
affiliation:
 - "Mimar Sinan University"
keywords: "inflation rate; shiny; SparkR; shiny-SparkR; web scraping"
packages: "SparkR; shiny; ggplot2; rvest"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

All official statistics centre or central banks of countries are
calculating inflation rate in monthly period. Inflation is measured by
the consumer price index inclueds the annual percentage change in the
cost to the average consumer of acquiring a basket of goods and services
for specific intervals, such as yearly. The central banks and the
statistics centres serve these information publicly. Most of the
institutes serve the information monthly. Its hard to track Inflation
rates for "Fast-Moving Consumer Goods(FMCG)" daily. To monitor this, I
created *SparkR-shiny* App. The application is scraping top FMCG related
web sites in daily based and stored the data on Spark stand alone
cluster on Amazon Web Services (AWS) Elastic Compute Cloud (EC2),
calculating consumer price index and day on day, month on month or year
on year changes based on FMCG categories, visiualizing the results
according to user defined criteria. With this application people could
filter consumer price index for any time interval, any category also
people could compare index changes of goods in different categories.

<!--  -->
<!-- **References** -->
<!-- International Monetary Fund -->
