---
title: "R Shiny for Real-time Analytics and Insight Delivery – A Solution for Complex Data in Agriculture"
author:
 - name: "Ming Shan"
   affiliation: [1]
   email: "ming.shan@kynetec.com"
   contact: yes
affiliation:
 - "Kynetec"
keywords: "Bayesian; big data; choice modeling; complex survey; real-time; shiny; simulation; small area estimation; spatial; statistical learning; supervised; unsupervised; visualization"
packages: "bayesm; cluster; dplyr; fields; ggplot2; kohonen; lme4; leaflet; magrittr; maps; maptools; party; rgdal; rgeos; sp; spatstat; shiny"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

One of the key challenges to successfully harness the value of big data
is to uncover the critical insight through analytics and make it easily
accessible to decision markers in an intuitive way. **R** *shiny* offers a
platform for developing an end-to-end solution completely within **R** from
mining the data with many modeling choices to insight delivery via
powerful and dynamic data visualization. Such solution is highly
suitable for agricultural data which is vast and dynamic, and
increasingly abundant due to the recent development and adoption of
precision farming and the related technologies. We would like to
illustrate a *shiny* application that integrates a mixture of privately
collected and governmental data across many key dimensions such as time,
different geographic levels, crops and product types. Analytics
including both supervised and unsupervised modeling capabilities and
other approaches such as small area estimation, spatial analysis and
complex survey estimation are included. Among many other specific
examples is an application of discrete choice modeling using
hierarchical Bayesian estimation to capture the preference of brand or
product features and the price sensitivity by small geographic units and
also allow the users to conduct market simulation by changing product
mixture and prices. All the analytics are made and delivered in
real-time.

<!--  -->
<!--  -->
<!--  -->
