---
title: "Multivariate analysis of variance for functional data using R"
author:
 - name: "Tomasz Górecki"
   affiliation: [1]
   email: "tomasz.gorecki@amu.edu.pl"
   contact: yes
 - name: "Łukasz Smaga"
   affiliation: [1]
affiliation:
 - "Adam Mickiewicz University"
keywords: "functional data; multivariate analysis of variance"
packages: "fda"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

We develop two testing procedures for multivariate analysis of variance
problem for functional data. Similarly as the one-way analysis of
variance for such data, this problem seems to be of practical interest.
The first method approximates the functional data from each
observational unit with of linear combination of orthonormal basis. Then
time is integrated out from the usual MANOVA sum-of-squares and
cross-products matrices. The null distribution of the standard MANOVA
statistics are determined by permutation. In the second test, the
functional data from each observational unit are projected on
 $\mathbb{R}^p$. Then, standard or permutation MANOVA tests are applied
to the projected data. The main rationale for this test is that equality
of the mean-functions vectors does not hold if equality of mean vectors
does not hold for any random projection of the mean-function vectors.
The performance of these methods is examined in comprehensive simulation
studies. The results suggest that the tests can detect small differences
between vectors of curves even with small sample sizes. We demonstrate
how these methods can be performed efficiently in **R** by applying them to
real world data. We implement these methods for **R** in our forthcoming
package.

<!--  -->
<!-- **References** -->
<!-- \begin{thebibliography}{12}
 \bibitem{CAFB2010} Cuesta-Albertos, J.A., Febrero-Bande, M. (2010) A simple multiway ANOVA for functional data. Test 19, 537--557.
 
 \bibitem{GS2015} G\'orecki, T., Smaga, \L. (2015) A comparison of tests for the one-way ANOVA problem for functional data. Comput. Statist. 30, 987--1010. 
 
 \bibitem{GS2016} G\'orecki, T., Smaga, \L., Multivariate analysis of variance for functional data (under review)
 
 \bibitem{HK} Horv\'ath, L., Kokoszka, P. (2012) Inference for functional data with applications. Springer, New York.
 
 \bibitem{Retal2009} Ramsay, J.O., Hooker, G., Graves, S. (2009) Functional data analysis with R and MATLAB. Springer, Berlin.
 
 \bibitem{RWGHfda2014} Ramsay, J.O., Wickham, H., Graves, S., Hooker, G. (2014) fda: Functional data analysis. R package version 2.4.3. \url{http://CRAN.R-project.org/package=fda}
 
 \bibitem{RCoreTeam2015} R Core Team (2015) R: a language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. \url{http://www.R-project.org/}
 
 \bibitem{Z2013} Zhang, J.T. (2013) Analysis of variance for functional data. Chapman $\&$ Hall, London.
 \end{thebibliography} -->
