---
title: "Using R to incorporate data science into the undergraduate statistics curriculum"
author:
 - name: "Paul Roback"
   affiliation: [1]
   email: "roback@stolaf.edu"
   contact: yes
affiliation:
 - "St. Olaf College"
keywords: "undergraduate curriculum; statistical computing; data science"
packages: "ggplot2; dplyr; ISLR"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

The American Statistical Association recently endorsed an updated set of
Curriculum Guidelines for Undergraduate Programs in Statistical Science, and the
first key point is: 'Increased importance of data science'. In addition
to traditional topics in statistical reasoning, modeling, and inference,
today’s future statisticians also need the ability to access and
manipulate data and to engage in algorithmic problem-solving to maximize
their contributions. In this talk, I will explore what the increased
importance of data science means for undergraduate programs in
statistics and describe what we have done using **R** at St. Olaf College,
an undergraduate institution of 3000 students in the United States. For
example, statisticians partnered with colleagues in computer science to
develop a 'statistics-infused' version of introductory computer science
(CS125). This new statistical computing course introduces students to
key foundational ideas in computer science by using mostly **R** (and some
Python) and motivating the ideas through a data analysis context.
Students learn about functions, loops, matrices, text strings, data
scraping, and SQL while also discovering data visualization and
classification methods. In fact, this course is one of seven featured in
The American Statistician article 'Data science in the statistics
curricula: preparing students to 'think with data''. In addition to CS125, we have integrated more data wrangling and
data visualization into our regression course, added a course on
Algorithms for Decision Making which primarily explores classification
methods using **R**, and developed an entire course on Data Visualization
with **R** to pilot this fall.

<!--  -->
<!-- **References** -->
<!-- Hardin J, Hoerl R, Horton N, Nolan D, Baumer B, Hall-Holt O, Murrell P, Peng R, Roback P, Temple Lang D, Ward M. (2015). Data science in the statistics curricula: preparing students to “think with data”. The American Statistician 69(4): 343-353. -->
