---
title: "Application of Artificial Neural Network to Planar Chromatography Data"
author:
 - name: "Dimitri Fichou"
   affiliation: [1]
   email: "dimitrifichou@gmail.com"
   contact: yes
 - name: "Dimitri Fichou; Gertrud Morlock"
   affiliation: [2,3]
affiliation:
 - "Justus Liebig University Giessen, Germany"
keywords: "Chemometrics; Neural Network; Planar Chromatography"
packages: "deepnet; jpeg; abind; EBImage"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Planar chromatography has a unique specificity compared to other
chromatographic techniques, i. e. the data format is a picture, in which
each pixel has quantitative and qualitative properties that corresponds
to the molecular reality in the physical word. This results in a greater
amount of data points that allows the use of high-level machine learning
algorithms like artificial neural network. Restricted Boltzmann Machine
was used on planar chromatograms for denoising and classification. For
both, no other preprocessing than a normalization between 0 and 1 was
needed. The denoising task took as input patches of pixels; when
crossing the network, the noise is removed and only the signal remains.
For the classification task, several layers of this neural network were
stacked together in order to analyze vertical bands of pixels. The last
layer of this network discriminated the two classes of the dataset with
an accuracy of 85 % when compared to human decisions.

<!--  -->
<!-- **References** -->
<!-- @article{Hinton2006,
 archivePrefix = {arXiv},
 arxivId = {20},
 author = {Hinton, G. E. and Salakhutdinov, R. R. and Salakhutdinov, G. E. Hinton* and R. R.},
 doi = {10.1126/science.1229223},
 eprint = {20},
 isbn = {0036-8075},
 issn = {0036-8075},
 journal = {Sciences},
 number = {March},
 pages = {1095--1099},
 pmid = {23287718},
 title = {{Reducing the Dimensionality of Data with Neural Networks}},
 volume = {339},
 year = {2006}
 }
 
 @article{Komsta2009,
 author = {Komsta, {\L}ukasz},
 doi = {10.1016/j.aca.2009.03.042},
 isbn = {00032670},
 issn = {00032670},
 journal = {Analytica Chimica Acta},
 number = {1-2},
 pages = {52--58},
 pmid = {19393366},
 title = {{A comparative study on several algorithms for denoising of thin layer densitograms}},
 volume = {641},
 year = {2009}
 }
 
 @article{Morlock2014,
 author = {Morlock, Gertrud E. and Ristivojevi{\'{c}}, Petar and Chernetsova, Elena S.},
 doi = {10.1016/j.chroma.2013.12.053},
 isbn = {0021-9673},
 issn = {00219673},
 journal = {Journal of Chromatography A},
 pages = {104--112},
 pmid = {24440096},
 publisher = {Elsevier B.V.},
 title = {{Combined multivariate data analysis of high-performance thin-layer chromatography fingerprints and direct analysis in real time mass spectra for profiling of natural products like propolis}},
 url = {http://dx.doi.org/10.1016/j.chroma.2013.12.053},
 volume = {1328},
 year = {2014}
 } -->
