---
title: "Reporting automation with ReporteRs"
author:
 - name: "David Gohel"
   affiliation: [1]
   email: "david.gohel@ardata.fr"
   contact: yes
 - name: "David Gohel"
   affiliation: [2,3]
affiliation:
 - "1. ArData"
keywords: "reporting; word; powerpoint; tables; graphics"
packages: "ReporteRs; rtable"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

R usage has risen in companies and reporting capabilities of R is now an
important subject. The way results are compiled in documents and spread
to colleagues or customers can be time consuming. Key points are
reproducibility, ability to produce pretty outputs and document types.

Microsoft document formats are still pretty ubiquitous in corporate
environments. The package ReporteRs make easier the production of these
documents on any platform. R users can produce pretty formatted outputs
into Word or PowerPoint documents with only R code. It comes with an API
to produce advanced graphical and tabular reporting.

In this talk, I will introduce ReporteRs and others related packages.
Major features will be explained and illustrated. A use case will be
presented to show a clinical reporting application made with shiny.

<!--  -->
<!--  -->
<!--  -->
