---
title: "R as an effective data mining tool in chemistry"
author:
 - name: "Anna Rybińska"
   affiliation: [1]
   email: "rybinska@qsar.eu.org"
   contact: yes
 - name: "Anna Rybinska; Katarzyna Odziomek; Tomasz Puzyn"
   affiliation: [2,3]
affiliation:
 - "Laboratory of Environmental Chemometrics, Faculty of Chemistry, University of Gdansk, Wita Stwosza 63, 80-308 Gdansk, Poland"
keywords: "data mining; predictive modeling; ionic liquids; chemometrics"
packages: "ggplot2; stats; dendextend; matrixStats; Matrix; MASS; klaR; cluster; dplyr; FWDselect"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

The vast amount of digital information generated every day in social
media, industry and academia necessitates the use of advanced techniques
enabling the processing, analysis and interpretation of data. A
significant amount of data is generated during various types of chemical
experiments. In this work, we present a workflow for predictive modeling
of physical-chemical properties of a diverse group of chemicals (ionic
liquids, ILs). Using selected chemometric methods, available in the most
popular R packages, we analyze the chemical data, model key
physical-chemical properties and validate the results. Moreover, the
presented approach enables the evaluation of the raw data quality. We
choose two unsupervised methods for data exploration: hierarchical
cluster analysis (HCA) and principal component analysis (PCA). Multiple
linear regression technique (MLR) was chosen as the example of a
modeling technique.

<!--  -->
<!--  -->
<!--  -->
