---
title: "R in the Mittelstand: Bringing Data Science to small and mid-size companies"
author:
 - name: "Oliver Bracht"
   affiliation: [1,2]
   email: "oliver.bracht@eoda.de"
   contact: yes
 - name: "Oliver Bracht"
   affiliation: [1,3]
affiliation:
 - "eoda GmbH, Chief Data Scientist"
keywords: "Implementing R; R in Business"
packages: "NA"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Most success stories of R in business are told by either new economy
companies or large international enterprises. However, there is another
field where R can enable success. Small to midsize, mostly family owned,
old economy companies: the Mittelstand. Besides its size, Mittelstand
companies are characterized by their organisational culture, their value
sets and their management philosophies. Hence, the introduction of Data
Science in general and R in particular to Mittelstand companies needs to
consider this specific characteristic in order to be successful. This
talk will focus on patterns that Mittelstand companies typically follow
when they implement R. Main challenges of the process as well as road
blockers on the way will be pointed out. It will give practical advice
with real world examples and finally propose strategies of how to
achieve long term success.

**References**

NA
