---
title: "brms: An R Package for Bayesian Multilevel Models using Stan"
author:
 - name: "Paul-Christian Buerkner"
   affiliation: [1,2]
   email: "paul.buerkner@gmail.com"
   contact: yes
 - name: "Paul-Christian Buerkner"
   affiliation: [1,3]
affiliation:
 - "NA"
keywords: "Bayesian inference; multilevel model; MCMC, Stan; R"
packages: "brms"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

The brms package implements Bayesian multilevel models in R using the
probabilistic programming language Stan. A wide range of distributions
and link functions are supported, allowing to fit -- among others --
linear, robust linear, binomial, Poisson, survival, ordinal,
zero-inflated, hurdle, and even non-linear models all in a multilevel
context. Further modeling options include autocorrelation of the
response variable, user defined covariance structures, censored data, as
well as meta-analytic standard errors. Prior specifications are flexible
and explicitly encourage users to apply prior distributions that
actually reflect their beliefs. In addition, model fit can easily be
assessed and compared with the Watanabe-Akaike-Information Criterion and
leave-one-out cross-validation.

**References**

NA
