---
title: "Unattended SVM parameters fitting for monitoring nonlinear profiles"
author:
 - name: "Emilio L. Cano"
   affiliation: [1,2]
   email: "emilio@lcano.com"
   contact: yes
 - name: "1. Emilio L. Cano; 2. Javier M. Moguerza; 3. Mariano Prieto Corcoba"
   affiliation: [1,3]
affiliation:
 - "1. The University of Castilla-La Mancha; 2. Rey Juan Carlos University; 3; ENUSA Industrias Avanzadas"
keywords: "Quality Control; SVMs; nonlinear profiles"
packages: "SixSigma; e1071; qcc"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

The monitoring of nonlinear profiles is a recent quality control
technique. It allows to apply Statistical Process Control (SPC) methods
to processes in which, rather than having a quality characteristic,
there is a sort of nonlinear function that characterises the process.
This method has been implemented in the SixSigma R package \[1\], and
explained in depth in \[2\]. The underlying idea is to compute a
prototype profile and confidence bands using a data set from an
in-control process, monitoring subsequent profiles thereafter. Thus, the
same methodology used in well-known Shewhart control charts can be
applied to complex processes. To this aim, raw data can be used.
Nevertheless, using regularisation theory nonlinear profiles can be
smoothed in order to better represent and analyse the profiles. In this
work, we use Support Vector Machines (SVMs) \[3\] to smooth profiles
throughout the control process. Consequently, SVM parameters must be
selected in order to reach a good fit of the nonlinear function at hand.
Such parameters, namely: C and epsilon, can be explicitely assigned in
the smoothProfile function of the SixSigma package. However, a quality
control practicioner seldom knows about SVMs, needless to say that they
have no time to spend modelling functions. Hence, we rely on \[4\] to
automatically fit the SVM parameters using the process data, thereby
achieving unattended SVM fitting. Furthermore, noise is previously
estimated by means of a \`loess' fit.

**References**

\[1\] Cano EL, Moguerza JM and Redchuk A (2012). Six Sigma with R.
Statistical Engineering for Process Improvement, volume 36 series Use R!
Springer, New York. \[2\] Cano EL, Moguerza JM and Prieto M (2015).
Quality Control with R. An ISO Standards Approach, series Use R!
Springer. \[3\] Moguerza, J.M., Muñoz, A. (2006). Support Vector
Machines with applications. Stat. Sci. 21(3), 322-336 \[4\] Cherkassky,
V and Ma, Y (2004). Practical selection of SVM parameters and noise
estimation for SVM regression. Neural Networks, 17(1), 113-126
