---
title: "Power of Java's RSession and rKafka in the data science team collaboration"
author:
 - name: "Paweł Cejrowski"
   affiliation: [1,2]
   email: "pcejrowski@gmail.com"
   contact: yes
 - name: "Paweł Cejrowski"
   affiliation: [1,3]
affiliation:
 - "Grupa Wirtualna Polska"
keywords: "integration; microservices; rsession; kafka; team collaboration"
packages: "rkafka;"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

The times of single geniuses able to solve most advanced problems of the
technical industry passed away. Nowadays, it is necessary to collaborate
and support each other within teams. When it comes to Data Science
teams, they are cross-functional and consist of people possessing
different skills and having different duties. When working on a single
product mathematicians, statisticians and engineers have to find right
ways of exchanging and interfacing their piece of work. Unfortunately,
not only they think differently, but they also use different platforms
and languages. It implies in creating solutions for integration. One
well known way of co-working is embedding code in different language in
your own software. As an example, R code can be invoked from Java family
languages using RSession. Another way of collaboration is passing
messages throughout a middleware. Best known messaging system is Apache
Kafka, originally developed by Linkedin. It is distributed among cluster
nodes and allows high-throughput in a publish-subscribe manner and what
is more important can be accessed from R code using rKafka package. \\
In my presentation, I am going to familiarize you with those subjects
and prepare for using them in production. There are a few tricks that
will make your life easier.

**References**

NA
