---
title: "Machine learning modeling of phenological phases in Poland"
author:
 - name: "Bartosz Czernecki"
   affiliation: [1,2]
   email: "nwp@amu.edu.pl"
   contact: yes
 - name: "Bartosz Czernecki; Jakub Nowosad; Katarzyna Jabłońska"
   affiliation: [1,3]
affiliation:
 - "1. Adam Mickiewicz University in Poznań, Department of Climatology; 2. Adam Mickiewicz University, Department of Geoinformation; 3. Institute of Meteorology and Water Management - National Research Institute"
keywords: "phenology; machine learning; modeling; satellite; meteorology; climatology"
packages: "caret; raster; Boruta; parallel"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Changes in timing of phenological phases are important proxies in
contemporary climate research. The aim of the study was to create and
evaluate different statistical models for reconstructing and predicting
the selected phenological phase within caret R package. Three types of
data sources were applied as predictors: (i) satellite derived products,
(ii) preprocessed gridded meteorological data, and (iii) spatial
features (longitude, latitude, altitude) of the monitoring sites. The
obtained results showed potential for coupling meteorological derived
indices with remote sensing products in terms of phenological (late
spring) modelling. It was also shown that choosing a specific set of
predictors and applying a robust preprocessing procedures is more
affecting final results than applying a statistical model.

**References**

NA
