---
title: "Discrete Choice Models in R"
author:
 - name: "Daniel Guhl"
   affiliation: [1,2]
   email: "daniel.guhl@hu-berlin.de"
   contact: yes
 - name: "1. Daniel Guhl; 2. Sebastian Gabel"
   affiliation: [1,3]
affiliation:
 - "1. Humboldt University Berlin; 2. Humboldt University Berlin"
keywords: "Discrete choice models; Econometrics; Bayesian statistics; Stan"
packages: "Stan; mlogit; gmnl; bayesm; ChoiceModelR; RSGHB"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Discrete choice models (DCM) are a widely used class of models in
Economics, Marketing, and Transportation Science. These models are
rooted in random utility theory (McFadden 1974) and can be applied if a
decision maker picks one alternative out of multiple options. The most
commonly used variations of DCM (Train 2009) are the multinomial logit
model (MNL), the mixed logit model (MXL), and multinomial probit (MNP).
Many R packages (e.g., mlogit, gmnl, bayesm) are available for
frequentist and Bayesian inference of DCM. However, the dif- ferent
packages lack a unified data interface, common structure of functions
and methods, and comparable output. Therefore, the analyst is faced with
a typical dilemma: To test several mod- els and follow established
research processes (and maybe fulfill reviewer requests) one has to deal
with data transformations, model translations, and output formatting,
which is tedious, time consuming, and error-prone. In addition, the
established R-packages lack flexibility and trans- parency. To this end,
we propose to use Stan, a general purpose modeling language for Bayesian
inference written in C++ with interfaces to R, python, Matlab, Julia,
and Stata. We compare Stan-implementations of MNL and MXL models using
simulated and real data. We show how Stan can be used for estimating
more sophisticated models (e. g., models in willingness-to-pay space,
Sonnier et al. 2007). We also provide a quick reference over our R
package DCM that aims at closing the gap for existing packages regarding
a unified data API and comparable model output.

**References**

1.  McFadden, D. (1974). Conditional logit analysis of qualitative
    choice behavior. In Zarembka, P., editor, Frontiers in Econometrics,
    chapter 4, pages 105–142. Academic Press, New York.
2.  Sonnier, G., Ainslie, A., and Otter, T. (2007). Heterogeneity
    distributions of willingness-to-pay in choice models. Quantitative
    Marketing and Economics, 5(3):313–331.
3.  Train, K. E. (2009). Discrete choice methods with simulation.
    Cambridge University Press, New York, 2nd edition.
