---
title: "Text Mining in R"
author:
 - name: "Christoph Hoffmann"
   affiliation: [1,2]
   email: "christoph.hoffmann@appstam.com"
   contact: yes
 - name: "Christoph Hoffmann"
   affiliation: [1,3]
affiliation:
 - "Appstam Consulting GmbH"
keywords: "Text Mining, Classification, Sentiment Analysis"
packages: "tm; e1071, twitteR"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

I would like to present the Text Mining cababilities of R. In particular
the framework for Text Analysis with R provided by the tm package.
Furthermore I show the publicly available API for Twitter. Then I will
continue with a Case Study of Sentiment Analysis of Twitter Data /
Feedback Data. This is done with Naive Bayes Classification and/or
Logistic Regression. The Case Study involves all the steps from
obtaining raw text data to manipulating the data to running the actual
algoritms adapted for text data. A bit of theory is provided to motivate
the use of the Bayesian Classifier and if time allows I will run model
comparisons. As i've seen that your Workshops are already heavily
booked, we could also consider to offer it as a workshop.

**References**

1.Speech and Language Processing: An introduction to natural language
processing, computational linguistics, and speech recognition. Daniel
Jurafsky & James H. Martin. 2. A text mining framework in R and its
applications. Doctoral thesis, WU Vienna University of Economics and
Business. Feinerer, Ingo (2008) 3. Text Mining - Predictive Methods for
Analyzing Unstructured Information. Weiss et al.
