---
title: "cgmisc: enhanced genome-wide association analyses and visualization"
author:
 - name: "Jagoda Jabłońska"
   affiliation: [1,2]
   email: "jagoda100jablonska@gmail.com"
   contact: yes
 - name: "1.Jagoda Jabłońska;2.Marcin Kierczak;3.Simon Forsberg"
   affiliation: [1,3]
affiliation:
 - "1.University of Warsaw;2.Uppsala University;3.Swedish University of Agricultural Sciences"
keywords: "GWAS;bioinformatics;visualization;sequencing"
packages: "cgmisc; GenABEL"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

High-throughput genotyping and sequencing technologies facilitate
studies of complex genetic traits and provide new research
opportunities. The increasing popularity of genome-wide association
studies (GWAS) leads to the discovery of new associated loci and a
better understanding of the genetic architecture underlying not only
diseases, but also other monogenic and complex phenotypes. Several
softwares are available for performing GWAS analyses, R environment
being one of them. We present cgmisc, an R package that enables enhanced
data analysis and visualization of results from GWAS. The package
contains several utilities and modules that complement and enhance the
functionality of the existing software. It also provides several tools
for advanced visualization of genomic data and utilizes the power of the
R language to aid in preparation of publication-quality figures. Some of
the package functions are specific for the domestic dog (Canis
familiaris) data but are easy to adjust for analysing other species.

**References**

1.  Kierczak M, Jabłońska J, Forsberg SKG, et al. (2015) cgmisc:
    enhanced genome-wide association analyses and visualization.
    Bioinformatics, 31, 3830-3831.
2.  Aulchenko Y.S., et al. (2007) GenABEL: an R library for genome-wide
    association analysis. Bioinformatics, 10, 1294–1296.
