---
title: "Using R for artistic purposes"
author:
 - name: "Päivi Julin"
   affiliation: [1,2]
   email: "julin@apup.org"
   contact: yes
 - name: "Päivi Julin"
   affiliation: [1,3]
affiliation:
 - "Aureolis"
keywords: "Visualization; design; typography; alternative; Processing;"
packages: "ggplot2; grid; Rserve; RColorBrewer;"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

R can be tamed for serious business usage and data analysis, but this
tool also has abilities for a different kind of approach: creating data
art. Even R might not be mainly marketed with its graphics; it does have
competence in genuine creativeness for unusual visualizations. Thus, R
is much more than just bar plots, charts and maps – it is only a matter
of practice and adaptation.

Data art focuses using raw data to produce visualizations with both
aesthetic and informative scope. Having a creative process with digital
media, real-time data and R, may lead to producing alternative
interpretations from traditional information. Playing with R graphics
devices, one is able to adjust any kind of visual presentations inside R
console. Another option is to handle data manipulation with R and print
output with alternative graphic portals - such as Processing or D3.

The presentation involves graphical visualizations, technical solutions,
and general ideas, how to use R in alternative ways. Telling a story
from data is a fun journey, therefore playing with R can be rather an
amusing R-experience. This program being my muse, the aim is to inspire
others.

**References**

-
