---
title: "EnvCpt: An R package for changepoint identification in Environmental data"
author:
 - name: "Rebecca Killick"
   affiliation: [1,2]
   email: "r.killick@lancs.ac.uk"
   contact: yes
 - name: "Rebecca Killick; Claudie Beaulieu; Simon Taylor"
   affiliation: [1,3]
affiliation:
 - "Lancaster University; University of Southampton; Lancaster University"
keywords: "model selection; changepoints; nonstationary time series; environment; oceanography; climate science"
packages: "EnvCpt; changepoint"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

 Man-made pressure on the Earths climate and ecosystems is increasing
vulnerability to abrupt changes, which can be especially
socio-economically challenging given the rapidity at which an ecosystem
switches from one state to another relative to the time spent in the
different states (e.g. a shift from one year to the next that persists
on decadal or longer time scales). The ecosystem shift can be a response
to change in external forcing (e.g. climate shift) or a random
reorganization of the system, which can often be characterized by a
simple autoregressive process. The distinction between stochastic and
deterministic regime shifts is fundamental to gain a better
understanding of the underlying mechanisms. In the climate and
oceanography literature, the detection of regime shifts is commonly made
using a sequential algorithm to test for shifts in the mean . However,
this methodology can lead to spurious regime shift detection in the
presence of autocorrelation, which is typically present in climate and
environmental time series. Furthermore, a trend (e.g. long-term climate
change) may be falsely interpreted as a series of regime shifts using
this methodology. The EnvCpt R package presents a flexible methodology
able to discern between the presence of mean, trend and autocorrelation
and any combination of multiple shifts therein. The benefit of the
package is that an automatic choice is made between whether trend,
autocorrelation or changepoint models best fit the data using model
selection. Thus no visual inspection of the data is required unlike
current methods.

**References**

@Article{rodionov2006, Title = {Use of prewhitening in climate regime
shift detection}, Author = {Rodionov, Sergei N}, Journal = {Geophysical
Research Letters}, Year = {2006}, Number = {12}, Volume = {33},

Publisher = {Wiley Online Library} } @Article{rodionov2004, Title = {A
sequential algorithm for testing climate regime shifts}, Author =
{Rodionov, Sergei N}, Journal = {Geophysical Research Letters}, Year =
{2004}, Number = {9}, Volume = {31},

Publisher = {Wiley Online Library} }
