---
title: "stplanr: an R package for transport planning"
author:
 - name: "Robin Lovelace"
   affiliation: [1,2]
   email: "r.lovelace@leeds.ac.uk"
   contact: yes
 - name: "Robin Lovelace"
   affiliation: [1,3]
affiliation:
 - "University of Leeds"
keywords: "transport, GIS, modelling, visualisation"
packages: "stplanr, leaflet, shiny"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

**stplanr** was developed to solve a real world problem: how to convert
official data on travel patterns into geographic objects that could be
plotted on a map and analysed using GIS? Over time the package has
evolved to include a number of other functions. Analysis of road traffic
casualty data, various routing algorithms, 'travel watershed' analyis
and access to Google's Travel Matrix are all possible. This paper traces
the development of these capabilities with a focus on applied case
studies and reproducible examples.

**References**

Cheshire, James, and Robin Lovelace. 2015. “Spatial data visualisation
with R.” In Geocomputation, edited by Chris Brunsdon and Alex Singleton,
1–14. SAGE Publications. Iacono, Michael, Kevin J. Krizek, and Ahmed
El-Geneidy. 2010. “Measuring non-motorized accessibility: issues,
alternatives, and execution.” Journal of Transport Geography 18 (1).
Elsevier Ltd: 133–40. Kahle, D, and Hadley Wickham. 2013. “ggmap:
Spatial Visualization with ggplot2.” The R Journal 5: 144–61. Martínez,
L. Miguel, and José Manuel Viegas. 2013. “A new approach to modelling
distance-decay functions for accessibility assessment in transport
studies.” Journal of Transport Geography 26: 87–96. Waddell, Paul. 2002.
“UrbanSim: Modeling urban development for land use, transportation, and
environmental planning.” Journal of the American Planning Association 68
(3). Taylor & Francis: 297–314.
