---
title: "An R implementation of Kauffman's NK model"
author:
 - name: "Tomasz Owczarek"
   affiliation: [1]
   email: "tomasz.owczarek@polsl.pl"
   contact: yes
 - name: "Tomasz Owczarek"
   affiliation: [2,3]
affiliation:
 - "Silesian University of Technology, Faculty of Organization and Management"
keywords: "nk model; complexity; fitness landscape; agent-based modeling"
packages: "dplyr; ggplot2; igraph"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Stuart Kauffman's NK model (Kauffman, 1993) is a simple but powerful
model of complex system with many interactions between its elements. It
generates so called fitness landscape, i.e. a space consisted of many
points with different attractiveness (fitness). The great advantage of
the model is that only two parameters (N and K) are required to be
controlled to generate environments with “tunable complexity” (Rivkin,
2000) - from very simple with one local and global optimum to completely
random, with a large number of local optima. The NK model is used in the
studies of many phenomena in various fields e.g. biology (Kauffman,
1993), economics (Lenox et al., 2006), organizational studies (Porter,
Siggelkov, 2008) or engineering (Frenken, 2006). In my presentation I
would like to introduce an R package which implements the NK model and
show how to use it to generate fitness landscapes and explore their
properties for different influence matrices (Rivkin, Siggelkov, 2007).

<!--  -->
<!-- **References** -->
<!-- Frenken K., A fitness landscape approach to technological complexity, modularity, and vertical disintegration, "Structural Change and Economic Dynamics" 2006, vol. 17, no. 3, pp. 288-305.
 Kauffman S. A., The Origins of Order, Oxford Univeristy Press, New York, 1993.
 Lenox M. J., Rockart S. F., Lewin A. Y., Interdependency, Competition, and the Distribution of Firm and Industry Profits, "Management Science" 2006, vol. 52, no. 5, pp. 757-772.
 Porter M., Siggelkow N., Contextuality Within Activity Systems and Sustainability of Competitive Advantage, "Academy Of Management Perspectives" 2008, vol. 22, no 2, pp. 34-56.
 Rivkin J. W., Imitation of Complex Strategies, "Management Science" 2000, vol. 46, no. 6, pp. 824-844.
 Rivkin J. W., Siggelkow N., Patterned interactions in complex systems: Implications for exploration, "Management Science" 2007, vol. 53, no. 7, pp. 1068-1085. -->
