---
title: "Applying genetic algorithms to calibrate a processing chain for a Landsat-based time series analysis of disturbance - regrowth dynamics in tropical forests"
author:
 - name: "Fabián Santos"
   affiliation: [1,2]
   email: "fabian_santos_@hotmail.com"
   contact: yes
 - name: "Fabián Santos; Gunther Menz; Olena Dubvyky"
   affiliation: [1,3]
affiliation:
 - "University of Bonn"
keywords: "time-series analysis; genetic algorithms; Landsat; tropical forests monitoring"
packages: "GA; changepoint, BreakoutDetection, ecp"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

We present an innovative approach to calibrate processing chains
designed for a time-series analysis based on genetic algorithms (GA).
Using a case study of disturbance-regrowth monitoring employing Landsat
data in tropical forests located in the Amazonian region of Ecuador.
This area is characterized by mountainous terrain, high topographic
relief and extensive cloud cover. These conditions can cause noise in
the time-series of Landsat data and require different corrections before
its analysis. We describe here the use of GA to reduce calibration
uncertainties, enhance the output accuracy, and avoid unnecessary
processing caused by trial-and-error approaches in remote sensing.

**References**

1.  L. Scrucca, "GA: A Package for Genetic Algorithms in R," Journal of
    Statistical Software, vol. 53, pp. 1-37, 2013.
2.  R. Killick and I. A. Eckley, "changepoint: An R Package for
    Changepoint Analysis.," Journal of Statistical Software, vol.
    58, pp. 1-19, 2014.
3.  N. James, A. Kejariwal, and D. Matteson, "BreakoutDetection:
    Breakout Detection via Robust E-Statistics," R package version 1.0.1
    ed, 2014.
4.  N. James and D. Matteson, "ecp: An R Package for Nonparametric
    Multiple Change Point Analysis of Multivariate Data," Journal of
    Statistical Software, vol. 62, pp. 1-25, 2014.
