---
title: "Using R for backtesting algorithmic trading strategies on high-frequency data"
author:
 - name: "Piotr Wójcik"
   affiliation: [1,2]
   email: "pwojcik@wne.uw.edu.pl"
   contact: yes
 - name: "Piotr Wójcik"
   affiliation: [1,3]
affiliation:
 - "Faculty of Economic Sciences, University of Warsaw"
keywords: "algorithmic trading, high-frequency data, backtesting, efficient calculations"
packages: "xts; chron; quantmod; Rbbg; IBrokers; TFX; tseries; PerformanceAnalytics; caTools; TTR; inline; Rcpp; RcppArmadillo"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

\documentclass{article}
 
 \usepackage[sort]{natbib} 
 
 \title{Using R for backtesting algorithmic trading strategies on high-frequency data}
 \author{Piotr \textsc{W\'ojcik}\thanks{University of Warsaw, Faculty of Economic Sciences, \texttt{pwojcik@wne.uw.edu.pl}.}}
 \date{}
 
 
\begin{document}
 
 \maketitle
 
 \begin{abstract}
 
 \bibliographystyle{plainnat} 
 
 Along with the advances in computer technology high-frequency trading developed in 1990s and became widely popular since then. Traders started to build algorithms that use highly developed quantitative models to automatically determine when and where to trade. The profitability of trading strategies based on such algorithms needs to be verified on historical data (backtested) prior to its application in real life. Intraday data in finance may have large volumes (up to 1440 minutes or 86400 seconds of quotations every day, i.e. 20 millions of observations for one year). In addition developed algorithms are usually parametrized and their final version needs to be optimized with respect to these parameters. This introduces a possibly huge number of combinations that need to be compared with respect to selected performance measures. Large amounts of data and many variants of the algorithm require a computationally efficient tool that should also allow to relatively easily apply statistical models. And R together with C++ can provide such a tool . The presentation shows how R can be used to access intraday data and to develop and backtest different algorithmic trading strategies with the help of Rcpp family packages. For more details see for example \citet{article_eddelbuettel2011}, \citet{misc_paciorek2014}, \citet{book_georgakopoulos2015}, \citet{misc_dziubinski2016}, \citet{misc_eddelbuettel2016}. 
 
 \end{abstract}
 
 \bibliography{biblio_eRum}
 
 \end{document}

**References**

@article{article_eddelbuettel2011, 
  author = {Dirk Eddelbuettel and Romain Francois}, 
 title = {Rcpp: Seamless {R} and {C++} Integration}, 
 journal = {Journal of Statistical Software}, 
 number = {40}, 
 volume = 8, 
 pages = {1--18}, 
 year = 2011}
 
 @book{book_georgakopoulos2015,
  author = {Harry Georgakopoulos},
  title = {Quantitative Trading with {R}. Understanding Mathematical and Computational Tools from a Quant’s Perspective},
  publisher = {Palgrave Macmillan},
  year = 2015}
  
 @misc{misc_dziubinski2016,
  author = {Matt P. Dziubinski},
 title = {Getting the most out of {Rcpp}: High-Performance {C++} in Practice},
 note = {R in Finance 2016}, 
  year = 2016}
 
 @misc{misc_eddelbuettel2016,
  author = {Dirk Eddelbuettel and Romain Francois and Douglas Bates}, 
  title = {{RcppArmadillo}: {Rcpp} integration for {Armadillo} templated linear algebra library},
  note = {R package version 0.6.700.6.0, URL http://CRAN.R-Project.org/package=RcppArmadillo},
  year = 2016}
 
 @misc{misc_paciorek2014,
  author = {Chris Paciorek}, 
  title = {C++ for statisticians, with a focus on interfacing from {R} and {R} packages},
  note = {University of California, Department of Statistics workshop, http://www.stat.berkeley.edu/scf/paciorek-cppWorkshop.pdf},
  year = 2014}
