---
title: "R as a tool for graphical diagnostics in population pharmacokinetic modeling"
author:
 - name: "Agnieszka Borsuk"
   affiliation: [1]
   email: "borsuk.agnieszka@gmail.com"
   contact: yes
affiliation:
 - "Department of Biopharmaceutics and Pharmacodynamics, Medical University of Gdańsk"
keywords: "graphical model diagnostics; population pharmacokinetics"
packages: "ggplot2; lattice"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Population pharmacokinetic (PopPK) modeling aims at finding typical
pharmacokinetic parameters and their variability within a target
population of patients treated with a drug of interest. Population
approach to pharmacokinetic modeling is gaining popularity as it can
handle sparse data and estimate pharmacokinetic parameters of each
individual. Large datasets and complexity of the models hinder assessing
the quality of a model fit with a single numerical value. Graphical
analysis plays a unique role in PopPK since it enables a better insight
into the model structure. **R** is a powerful and versatile tool for
graphical model diagnostics. It offers variety of visualizations, allows
creating flexible scripts for quick model assessment and saving the
results as a formal report. The produced graphics are publication-ready
and meet the requirements for most non-standard and customized plots.

<!--  -->
<!--  -->
<!--  -->
