---
title: "R as a tool for geospatial modeling in large dataset - example of dasymetric modeling at a continental scale (United States)"
author:
 - name: "Anna Dmowska"
   affiliation: [1]
   email: "dmowska@amu.edu.pl"
   contact: yes
affiliation:
 - "Adam Mickiewicz University"
keywords: "geospatial data; large dataset; dasymetric modeling"
packages: "rgrass7; rgdal; RSQLite; sp"
# bibliography: bibliography.bib
output:  
        erum::erum_abstract:
                  keep_tex: TRUE
---

Geospatial raster datasets are usually large data structures. Thus its
processing requires algorithms that are both efficient and fully
automatic. The philosophy of development of GIS software offers many
solutions to a user. These solutions are conceptually limited which
means that they perform well in their native tasks but are difficult to
extend if the problem goes beyond its foundations. In such situations
computationally complex tasks require tailored software which is
difficult to develop without programming experiences. **R** language offers
extensive amount of tools designed to work with geospatial data like *sp*
library, as well as bindings to external data sources like *rgrass7*,
*rgdal*, *RSQLite*. Flexible nature of geospatial objects in **R** allows to
create a fully automatic procedure that complements GIS software without
long-term programing experiences. 

Here we present an automatic procedure
which was designed to work on high resolution datasets at a continental
scale: 11 million of records in tabular data and over 8 billion of grid
cells. To process such amount of data we automated our procedure by
dividing it into few steps: 

1. import and store Census data in SQLite database, 
2. preprocessing of geospatial data performed in GRASS GIS software, 
3. performing dasymetric modeling in **R**, 
4. propagation model for geospatial data and export geospatial data from **R** to GIS format to map population distribution.

Our results show that: 

1. **R** can perform such a calculation in a reasonable time (60 hours for the entire U.S.),
2. no additional intermediate layers or steps are required,
3. procedure is flexible: it can be reproduced regardless of the data scale.

<!--  -->
<!--  -->
<!--  -->
